# Generated by Django 4.1.3 on 2023-01-30 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idMunicipios', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id_economico', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('presupuesto_anual', models.IntegerField(blank=True, null=True)),
                ('monto_residencial', models.IntegerField(blank=True, null=True)),
                ('monto_residencial_industrial', models.IntegerField(blank=True, null=True)),
                ('presupuesto_campañas', models.IntegerField(blank=True, null=True)),
                ('ingresos_fiscales', models.IntegerField(blank=True, null=True)),
                ('ingresos_preasignaciones', models.IntegerField(blank=True, null=True)),
                ('ingresos_credito', models.IntegerField(blank=True, null=True)),
                ('ingresos_asistencia', models.IntegerField(blank=True, null=True)),
                ('ingresos_anticipos', models.IntegerField(blank=True, null=True)),
                ('ingresos_totales', models.IntegerField(blank=True, null=True)),
                ('ingresos_ambiental_fiscales', models.IntegerField(blank=True, null=True)),
                ('ingresos_ambiental_preasignaciones', models.IntegerField(blank=True, null=True)),
                ('ingresos_totales_ambiental', models.CharField(blank=True, max_length=45, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadoreconomico', to='economia.municipio')),
            ],
            options={
                'db_table': 'indicador_economico',
            },
        ),
    ]
