# Generated by Django 4.1.3 on 2023-01-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0002_remove_indicadoreconomico_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
