# Generated by Django 4.1.3 on 2023-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadorambiental',
            name='id_ambiental',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indicadoreconomico',
            name='id_economico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indicadorinstitucional',
            name='id_institucional',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indicadorsocial',
            name='id_social',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
