# Generated by Django 4.1.3 on 2023-01-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0013_alter_indicadorambiental_id_ambiental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='año',
            field=models.IntegerField(default=2020),
        ),
    ]
