# Generated by Django 4.1.3 on 2023-01-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0014_municipio_año'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='año',
        ),
    ]
