# Generated by Django 4.1.3 on 2023-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0015_remove_municipio_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorambiental',
            name='año',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='año',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='indicadorinstitucional',
            name='año',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='indicadorsocial',
            name='año',
            field=models.IntegerField(default=2020),
        ),
    ]
