# Generated by Django 4.1.3 on 2023-01-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0016_indicadorambiental_año_indicadoreconomico_año_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadorambiental',
            old_name='año',
            new_name='anio',
        ),
        migrations.RenameField(
            model_name='indicadoreconomico',
            old_name='año',
            new_name='anio',
        ),
        migrations.RenameField(
            model_name='indicadorinstitucional',
            old_name='año',
            new_name='anio',
        ),
        migrations.RenameField(
            model_name='indicadorsocial',
            old_name='año',
            new_name='anio',
        ),
    ]
