# Generated by Django 4.1.3 on 2023-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0017_rename_año_indicadorambiental_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorambiental',
            name='subindice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='subindice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='indicadorinstitucional',
            name='subindice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='indicadorsocial',
            name='subindice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
